# Generated by Django 6.0.1 on 2026-01-08 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('reason', models.TextField(verbose_name='请假原因')),
                ('evidence', models.ImageField(blank=True, null=True, upload_to='leaves/%Y/%m/', verbose_name='证明材料')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已准假'), ('rejected', '已驳回'), ('completed', '已销假')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
