# Generated by Django 6.0.1 on 2026-01-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_for',
            field=models.TextField(null=True, verbose_name='请假去向'),
        ),
    ]
