# Generated by Django 6.0.1 on 2026-01-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leaverequest_leave_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_for',
            field=models.TextField(verbose_name='请假去向'),
        ),
    ]
