# Generated by Django 6.0.1 on 2026-01-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_leaverequest_comment_alter_leaverequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='report_back_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际销假时间'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回'), ('canceled', '已撤销'), ('reported', '已销假')], default='pending', max_length=10),
        ),
    ]
