# Generated by Django 6.0.1 on 2026-01-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_leaverequest_report_back_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回'), ('canceled', '已撤销'), ('reported', '已销假'), ('returned', '退回修改')], default='pending', max_length=10),
        ),
    ]
