# Generated by Django 6.0.1 on 2026-01-09 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_remove_dormitory_radius'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=100, verbose_name='查寝配置名称')),
                ('check_date', models.DateField(verbose_name='查寝日期')),
                ('normal_start', models.TimeField(verbose_name='正常签到开始时间')),
                ('normal_end', models.TimeField(verbose_name='正常签到结束时间')),
                ('late_end', models.TimeField(blank=True, null=True, verbose_name='晚归截止时间')),
                ('valid_range', models.IntegerField(default=500, verbose_name='打卡有效范围（米）')),
                ('need_material', models.BooleanField(default=False, verbose_name='是否需要上传证明材料')),
                ('notify_normal_after_normal_end', models.BooleanField(default=True, verbose_name='正常结束后是否通知')),
                ('notify_late_after_late_end', models.BooleanField(default=False, verbose_name='晚归结束后是否通知')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_check_configs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '查寝配置',
                'verbose_name_plural': '查寝配置',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50, verbose_name='学生姓名')),
                ('lat', models.FloatField(verbose_name='打卡纬度')),
                ('lng', models.FloatField(verbose_name='打卡经度')),
                ('distance', models.FloatField(verbose_name='与寝室的距离（米）')),
                ('check_time', models.DateTimeField(verbose_name='打卡时间')),
                ('check_status', models.CharField(choices=[('normal', '正常'), ('late', '晚归')], max_length=10, verbose_name='打卡状态')),
                ('late_reason', models.TextField(blank=True, null=True, verbose_name='晚归理由')),
                ('material', models.FileField(blank=True, null=True, upload_to='attendance_materials/', verbose_name='证明材料')),
                ('msg', models.CharField(max_length=200, verbose_name='打卡备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.dormitory', verbose_name='寝室')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
                ('check_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='dorm_check_in.checkconfig', verbose_name='查寝配置')),
            ],
            options={
                'verbose_name': '打卡记录',
                'verbose_name_plural': '打卡记录',
                'unique_together': {('student', 'check_config')},
            },
        ),
    ]
