# Generated by Django 6.0.1 on 2026-01-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dorm_check_in", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkconfig",
            name="late_duration",
            field=models.IntegerField(default=0, verbose_name="晚归打卡时长（分钟）"),
        ),
        migrations.AddField(
            model_name="checkconfig",
            name="normal_duration",
            field=models.IntegerField(default=30, verbose_name="正常打卡时长（分钟）"),
        ),
        migrations.AlterField(
            model_name="checkconfig",
            name="late_end",
            field=models.TimeField(
                blank=True, editable=False, null=True, verbose_name="晚归截止时间"
            ),
        ),
        migrations.AlterField(
            model_name="checkconfig",
            name="normal_end",
            field=models.TimeField(
                editable=False, null=True, verbose_name="正常签到结束时间"
            ),
        ),
    ]
