# Generated by Django 6.0.1 on 2026-01-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dorm_check_in", "0002_checkconfig_late_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="check_status",
            field=models.CharField(
                choices=[("normal", "正常打卡"), ("late", "晚归打卡")],
                default="normal",
                max_length=10,
                verbose_name="打卡状态",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="distance",
            field=models.FloatField(verbose_name="与寝室距离（米）"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="material",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="attendance_materials/%Y/%m/%d/",
                verbose_name="证明材料",
            ),
        ),
        migrations.AlterField(
            model_name="checkconfig",
            name="normal_duration",
            field=models.IntegerField(verbose_name="正常打卡时长（分钟）"),
        ),
    ]
