# Generated by Django 6.0.1 on 2026-01-10 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dorm_check_in", "0003_alter_attendance_check_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkconfig",
            name="late_duration",
        ),
        migrations.RemoveField(
            model_name="checkconfig",
            name="normal_duration",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="msg",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="打卡备注"
            ),
        ),
        migrations.AlterField(
            model_name="checkconfig",
            name="late_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="晚归截止时间（若无晚归则不填）"
            ),
        ),
        migrations.AlterField(
            model_name="checkconfig",
            name="normal_end",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="正常签到结束时间"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="checkconfig",
            name="normal_start",
            field=models.DateTimeField(verbose_name="正常签到开始时间"),
        ),
    ]
