# Generated by Django 6.0.1 on 2026-01-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dorm_check_in", "0004_remove_checkconfig_late_duration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkconfig",
            name="notify_late_after_late_end",
        ),
        migrations.RemoveField(
            model_name="checkconfig",
            name="notify_normal_after_normal_end",
        ),
    ]
