# Generated by Django 6.0.1 on 2026-01-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "用户信息", "verbose_name_plural": "用户信息"},
        ),
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="出生日期"),
        ),
        migrations.AddField(
            model_name="user",
            name="college",
            field=models.CharField(blank=True, max_length=100, verbose_name="学院"),
        ),
        migrations.AddField(
            model_name="user",
            name="education_level",
            field=models.CharField(
                choices=[
                    ("undergraduate", "本科生"),
                    ("master", "硕士研究生"),
                    ("doctor", "博士研究生"),
                ],
                default="undergraduate",
                max_length=20,
                verbose_name="培养层次",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="grade",
            field=models.CharField(
                blank=True, help_text="如：2023级", max_length=10, verbose_name="年级"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="major",
            field=models.CharField(blank=True, max_length=100, verbose_name="专业"),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=11, verbose_name="联系电话"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "学生"),
                    ("teacher", "辅导员"),
                    ("admin", "管理员"),
                ],
                default="student",
                max_length=10,
                verbose_name="角色",
            ),
        ),
    ]
