# Generated by Django 6.0.1 on 2026-01-09 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_user_birthday_user_college_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to=settings.AUTH_USER_MODEL,
                verbose_name="辅导员",
            ),
        ),
    ]
