# Generated by Django 6.0.1 on 2026-01-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_user_birthday_user_college_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "男"), ("female", "女"), ("unknown", "保密")],
                default="unknown",
                max_length=10,
                verbose_name="性别",
            ),
        ),
    ]
