# Generated by Django 6.0.1 on 2026-01-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='instructor',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('counselor', '辅导员'), ('admin', '管理员')], default='student', max_length=10, verbose_name='角色'),
        ),
    ]
