# Generated by Django 6.0.1 on 2026-01-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_instructor_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="校内：宿舍号（如8舍302）；校外：具体街道及门牌号",
                max_length=255,
                verbose_name="住宿详细地址",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="dorm_type",
            field=models.CharField(
                choices=[("internal", "校内住宿"), ("external", "校外住宿")],
                default="internal",
                max_length=10,
                verbose_name="住宿标识",
            ),
        ),
    ]
