# Generated by Django 6.0.1 on 2026-01-09 12:17

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_address_user_dorm_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dormitory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="宿舍楼名称"
                    ),
                ),
                ("latitude", models.FloatField(verbose_name="中心点纬度")),
                ("longitude", models.FloatField(verbose_name="中心点经度")),
                (
                    "radius",
                    models.IntegerField(default=200, verbose_name="考勤半径(米)"),
                ),
            ],
            options={
                "verbose_name": "宿舍楼",
                "verbose_name_plural": "宿舍楼列表",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.user_avatar_path,
                verbose_name="用户头像",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(
                help_text="校内：仅填寝室号（如302）；校外：填完整详细地址",
                max_length=255,
                verbose_name="详细地址",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="dorm_type",
            field=models.CharField(
                choices=[("internal", "校内住宿"), ("external", "校外住宿")],
                max_length=10,
                verbose_name="住宿标识",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="dormitory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.dormitory",
                verbose_name="所属宿舍楼",
            ),
        ),
    ]
