# Generated by Django 6.0.1 on 2026-01-09 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_dormitory_user_avatar_alter_user_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dormitory',
            name='radius',
        ),
    ]
